[tool.poetry]
name = "discord-bot"
version = "0.1.0"
description = ""
authors = ["Mickael Fioretti <fioretti.mickael@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
